### ISSUE TITLE
Auto-toggle doesn't appear to work

### ISSUE THREAD

**Issue by bradydjohnson** [Quip13/No-Distractions-Full-Screen#14]
What does the Auto Toggle function do? If I understand correctly, it should switch to Fullscreen Mode when reviewing in full screen and then switch back to Windowed Mode when not in full screen.

I have Auto-Toggle enabled, and it does not behave this way.
<img width="542" alt="image" src="https://user-images.githubusercontent.com/6741590/79088274-bef21280-7d07-11ea-9467-fbacccb89eb8.png">

Awesome add-on, btw! Thank you!

**Comment by Quip13** [comment]
Thanks for the report! Yeah ideally that's how it's meant to work.
It should trigger when going from the deck screen or overview screen (screen with stats that shows after clicking on a deck) to reviews. And it should trigger again when you hit "D" (to go back to the deck screen), sync or finish reviews
It should support this addon as well (https://ankiweb.net/shared/info/1024346707) if you're using it

I suspect it's due to an addon conflict. Can you try selectively disabling them to figure out which one is causing the issue? Or post the addons your using and I can take a look

**Comment by bradydjohnson** [comment]
Gosh, now it's working as expected. I must've been tired or confused when I wrote this issue. Closing!
