### ISSUE TITLE
Windows taskbar still shows even when full screen is enabled.

### ISSUE THREAD

**Issue by posnum** [Quip13/No-Distractions-Full-Screen#4]
I tried the following, but it didn't work.

* "MS_Windows_fullscreen_compatibility_mode" to false
* Hardware acceleration to enabled

Windows 10 1903
Anki 2.1.21
NDFS 3.2.6

**Comment by Quip13** [comment]
Interesting - is the issue persistent even after restarting?
Windows sometimes bugs out and puts the taskbar over everything

**Comment by posnum** [comment]
Yes, I restarted Windows several times.

**Comment by Quip13** [comment]
Ok thanks for the info. Can you:
1) disable all other addons and see if the issue persists?
2) see if the issue occurs with any other fullscreen apps? E.g. fullscreen YouTube videos
3) enable widowed mode with always on top - does this mode cover the taskbar?

**Comment by posnum** [comment]
1. The issue persists.
2. The issue doesn't occur in fullscreen YouTube videos.
3. Yes. I can drag the Anki window over the taskbar.

**Comment by Quip13** [comment]
That's odd - I would think setting "MS_Windows_fullscreen_compatibility_mode" would work in nearly all instances.
In a future version of this addon, I'm going to try to get fullscreen mode to work similarly to how Youtube does it (browser-based) so that should hopefully fix this issue (and others). However this version will take a while
In the meantime since the stay-on-top setting seems to do it for you, I could add a config setting to enable stay-on-top in fullscreen mode as well. Unfortunately this would obscure all other windows until you un-toggle it. Not ideal, but could be used as a last resort.

Could also you try one more thing: on any Anki screen, press Ctrl+Shift+; It should open a console. Type `mw.showFullScreen()` Does the issue still persist? (`mw.showNormal()` will undo it)

**Comment by Quip13** [comment]
Oh to execute the command in the console, press Ctrl+Enter after typing it in

**Comment by posnum** [comment]
>Could also you try one more thing: on any Anki screen, press Ctrl+Shift+; It should open a console. Type mw.showFullScreen() Does the issue still persist? (mw.showNormal() will undo it)

Yes, this issue still persists after executing mw.showFullScreen().

**Comment by Quip13** [comment]
Ok in that case this is a bug with the GUI framework Anki is built on. I'll add a config option to enable always on top in fullscreen as a workaround.
I'll get to it later tonight.

Hopefully when I rewrite the addon to be browser based these issues will be resolved.
Thanks for reporting!

**Comment by Quip13** [comment]
Added config option in latest release. Let me know if you're still having issues

**Comment by posnum** [comment]
Thanks a lot! Fullscreen works perfectly with "MS_Windows_fullscreen_force_on_top" enabled!

**Comment by Quip13** [comment]
Ah I was able to recreate this issue with Windows scaling and/or Anki UI scaling at values that do not evenly divide your screen resolution. (e.g. 149% instead of 150%)
Can you confirm that you have similar settings?

I should have a fix soon that doesn't require forcing the fullscreen mode on top. I'll push it out later tonight.

**Comment by posnum** [comment]
* 3840 x 2160 screen resolution
* Windows scaling is 150%
* Anki "User interface size" is 120%.

**Comment by Quip13** [comment]
Great thanks for the info - with those settings I can reproduce the issue

It's not quite as simple as I thought, but that scale equates to 1.8x (1.5*1.2), which gives a scaled fullscreen resolution of 2133.3 x 1200 (3840x2160 /1.8)
Anki rounds this to 2133x1200, which is what it uses to calculate the fullscreen window size. So your window size is 3839.4 x 2160 (2133x1200 x 1.8), which becomes rounded to **3839**x2160, which is one horizontal pixel less than it should be
Windows only hides the taskbar if the window takes up the entire screen, so that 1 pixel was causing the issue.

This issue only occurs with very particular scales/resolutions, so thanks for your help. I'll push the fix in a bit and hopefully it solves the issue

**Comment by Quip13** [comment]
Let me know if the latest version works for you with "MS_Windows_fullscreen_force_on_top" disabled

**Comment by posnum** [comment]
Thanks again for your support! I have confirmed that v3.2.8 works perfectly with "MS_Windows_fullscreen_force_on_top" disabled.
