### ISSUE TITLE
-

### ISSUE THREAD

**Issue by kurkasr** [Quip13/No-Distractions-Full-Screen#48]

**Comment by rwmpelstilzchen** [comment]
With the fullscreen capability being built-in in 2.1.57, I suggest rethinking the purpose of this add-on.

**Comment by cocofoco** [comment]
The plugin would still be useful considering that there are still some issues with Fullscreen mode (https://docs.ankiweb.net/platform/windows/display-issues.html#full-screen).

Personally, when I use Qt6, I have to switch the driver in order to use the built-in Fullscreen, and this makes Anki more sluggish.
With ND plugin's Fullscreen works fine even with the default driver (which feels snappier).
