### ISSUE TITLE
Strange buttons behaviors since last update

### ISSUE THREAD

**Issue by aPaci95** [Quip13/No-Distractions-Full-Screen#9]
Hello there, let me say that your addon is simply wonderful, but from the last update i noticed that the answer buttons edited by this addon (Minimal Flat Big Buttons https://ankiweb.net/shared/info/1042429613) are super compressed in the center of the screen while usually they spread all across the screen (which is super useful if you have a touch pc and want to smash some reviews with those enormous buttons). Any idea why this happens?

![1234tgds](https://user-images.githubusercontent.com/25055620/77847376-ec45a900-71bc-11ea-8bb1-d1d89a3347c3.png)

**Comment by Quip13** [comment]
Ah thanks for the report.

The new way the addon renders actually makes a sub-window that only contains the answer buttons instead of stretching the bottom bar over the entire screen and making the background transparent (which was causing graphical issues for some users)
I took a look through the addon code and unfortunately the way it formats the buttons isn't that compatible with the way I'm showing them. I'll look into some alternatives, but it may take a bit since it isn't a straightforward fix.

In the meantime, if you want to use the old version it's available [here](https://github.com/Quip13/No-Distractions-Full-Screen/blob/v3.2.8/NDFS.ankiaddon)
I'll post here when I figure this issue out

**Comment by aPaci95** [comment]
Since I was the one who made that addon by editing the css of large and colorful buttons a bit through some guides found online, but i don't know much about CSS or programming in general, it's not a problem for me to edit the addon if you explain what should i change exactly to make it compatible! I think the problem is that i used vw to define the width and since the container is much smaller with this new update, the buttons are much smaller too.
Alternatively since i saw that with your last update you added custom answer buttons, if you want and have time, you could add a feature that allows the user to select different presets for the answer buttons, add the styling that i used in my addon (big fat buttons useful for review through touch), and i would delete my addon / make a redirect to yours. Something like merging my addon in yours. But i understand that this would require much work and you may not be interested or have the time to do it!

**Comment by Quip13** [comment]
Oh haha it's great to meet another GUI addon maker! I think the way you did it is perfectly valid, and I think it would be good if my addon supported dynamic layouts. I'm testing some solutions out, so hopefully you won't have to make any changes.

I think presets would also be a great idea - I'll look into it

**Comment by Quip13** [comment]
I improved compatibility with the latest version! It should work properly now, and dynamically resize.

However there's still a bug where it doesn't resize properly upon zooming with Anki Zoom. Unfortunately anything that uses view units (vh or vw) won't work properly. If you can modify your addon to use anything besides vh or vw (pixels, em, percentage all should work fine), it should work better with zoom.
